### ISSUE TITLE
Tests get included in build folder

### ISSUE THREAD

**Issue by bfla** [buccaneerai/rxjs-stats#28]
Running `yarn build` causes tests to be included in the build folder.  This shouldn't happen.

**Comment by mustyoshi** [comment]
https://github.com/buccaneerai/rxjs-stats/pull/32

**Comment by bfla** [comment]
👍 Thanks, Bradley!  It's nice to have another collaborator on the project! 😃 

Also, this PR made me realize that CircleCI isn't running tests on PRs from forks, so I'll have to figure that out...

**Comment by bfla** [comment]
This fix will go out in v1.2!
